export const projects = [
  {
    name: 'Web Portfolio',
    description: "You're here",
    type: 'Website',
    tags: ['TypeScript', 'Next.js', 'Tailwind CSS'],
    picture: 'web-portfolio.jpg',
    repoLink: 'https://github.com/tfkhdyt/web-portfolio',
  },
  {
    name: 'Full Stack Roadmap',
    description: 'Roadmap to become a Full Stack Developer',
    type: 'Website',
    tags: ['TypeScript', 'Next.js', 'NestJS'],
    picture: 'full-stack-roadmap.png',
    repoLink: 'https://github.com/tfkhdyt/full-stack-roadmap',
  },
  {
    name: 'LAM Final Project',
    description: 'Web app to solve some linear algebra and matrices problems',
    type: 'Website',
    tags: ['JavaScript', 'Next.js', 'Tailwind CSS'],
    picture: 'aljabarlinear.jpg',
    repoLink: 'https://github.com/tfkhdyt/tugas-akhir-aljabar-linier-matriks',
  },
  {
    name: 'Movie Bot',
    description: 'Telegram Bot to search movies information',
    type: 'Bot',
    tags: ['Node.js', 'JavaScript', 'Telegraf'],
    picture: 'movie-bot.jpg',
    repoLink: 'https://github.com/tfkhdyt/tfkhdyt-movie-bot',
  },
  {
    name: 'Bayarcoek',
    description: 'Automation script to encrypt all files inside a folder',
    type: 'CLI',
    tags: ['Node.js', 'JavaScript', 'Commander.js'],
    picture: 'bayarcoek.jpg',
    repoLink: 'https://github.com/tfkhdyt/bayarcoek',
  },
  {
    name: 'Coursework',
    description: 'All of my college coursework',
    type: 'Misc',
    tags: ['Java', 'C++', 'Pascal'],
    picture: 'tugas-kuliah.jpg',
    repoLink: 'https://github.com/tfkhdyt/tugas-kuliah',
  },
  {
    name: 'Anime Naon Ieu?',
    description: 'Telegram Bot to find anime details from a screenshot',
    type: 'Bot',
    tags: ['Node.js', 'JavaScript', 'Telegraf'],
    picture: 'anibot.jpg',
    repoLink: 'https://github.com/tfkhdyt/anime-naon-ieu',
  },
  {
    name: 'MovieDB',
    description: 'Web app to search movie information',
    type: 'Website',
    tags: ['JavaScript', 'Bootstrap'],
    picture: 'imdb.jpg',
    repoLink: 'https://github.com/tfkhdyt/imdb',
  },
  {
    name: '30 Hari Jago JavaScript',
    description: 'Web app to learn JavaScript in 30 days',
    type: 'Website',
    tags: ['JavaScript', 'Bootstrap'],
    picture: '30days.jpg',
    repoLink: 'https://github.com/tfkhdyt/30DaysJagoJavaScript',
  },
]
